services:
  hotels:
    build:
      context: BookingApp.Hotels.WebApi
      dockerfile: Dockerfile
    image: hotels:latest
    container_name: hotels_app
    env_file:
      - ./BookingApp.Hotels.WebApi/.env
    ports:
      - 8001:8080
    networks:
      - booking_network
    restart: always

  hotels_mongodb:
    image: mongo:7
    container_name: hotels_mongodb
    env_file:
      - hotels_mongodb.env
    volumes:
      - hotels_mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - booking_network
    restart: always


networks:
  booking_network:
    driver: bridge

volumes:
  hotels_mongodb_data: